const defaultLocalization = {
    "table": {
        "id": "№",
        "name": "Название",
        "code": "Код",
        "regionId": "Регион №",
        "region": "Регион",
        "costPerHour": "Стоимость за час",
        "directPayment": "Зарплата (на руки)",
        "personalIncomeTax": "НДФЛ",
        "insurancePremiums": "Страховые взносы",
        "vacationAllowance": "Резерв на оплату отпусков",
        "qualificationCosts": "Сертификация, обучение, квалификация",
        "obtainingWorkPermitsCosts": "Расходы на оформление разрешений на работу",
        "consumablesCost": "Расходы на инвентарь, расходные материалы",
        "crampedConditions": "Стесненные условия",
        "workerLaborCostPerUnit": "Трудозатраты Рабочих",
        "machineLaborCostPerUnit": "Трудозатраты Машин и Механизмов",
        "workerPaymentPerHour": "Оплата Рабочих за час",
        "workerPaymentPerUnit": "Оплата Рабочих за единицу",
        "machineOperationCostPerHour": "Эксплуатация Машин и Механизмов за час",
        "machineOperationCostPerUnit": "Эксплуатация Машин и Механизмов за единицу",
        "directCostPerUnit": "Прямые затраты за единицу",
        "note": "Заметки",
        "status": "Статус",
        "type": "Тип",
        "unitId": "Единица измерения",
        "unit": "Единица измерения",
        "parentId": "Базовая расценка",
        "parent": "Базовая расценка"
    },

    "diagram": {
        "group": "Группа",
        "name": "Название",
        "start": "Начало",
        "end": "Конец",
        "january": "Янв",
        "february": "Фев",
        "march": "Мар",
        "april": "Апр",
        "may": "Май",
        "june": "Июн",
        "july": "Июл",
        "august": "Авг",
        "september": "Сен",
        "october": "Окт",
        "november": "Ноя",
        "december": "Дек"
    },

    "menu": {
        "mainMenu": "Главное меню",
        "machines": "Машины и Механизмы",
        "workers": "Рабочие",
        "regions": "Регионы",
        "projects": "Проекты",
        "measurementUnits": "Единицы измерения",
        "unitPriceGuide": "Справочник единичных расценок",
        "tasks": "Задачи",
        "guide": "Справочники",
        "counterparties": "Контрагенты",
        "contractor": "Кабинет подрядчика",
        "admin": "Панель администратора",
        "settings": "Настройки",
        "instruction": "Обучение",
        "workingGroup": "Рабочая группа",
        "structure": "Структура",
        "pir": "ПИР",
        "networkScheduling": "КСП",
        "economics": "Экономика",
        "risks": "Риски",
        "contracting": "Контрактация",
        "finance": "Финансы",
        "construction": "Стройка",
        "reports": "Отчеты",
        "dashboards": "Дашборды",
        "diagram": "Диаграмма",
        "smtr": "ВМТР",
    },

    "upg": {
        "code": "Группа ЕР",
        "name": "Наименование ЕР",
        "unit": "Ед. изм.",
        "workerLaborCostPerUnit": "ТЗР",
        "machineLaborCostPerUnit": "ТЗМ",
        "workerPaymentPerHour": "ОР",
        "workerPaymentPerUnit": "ОР",
        "machineOperationCostPerHour": "ЭММ",
        "machineOperationCostPerUnit": "ЭММ",
        "directCostPerUnit": "ПЗ",
        "unitPrices": "Расценки",
        "enlargement1": "Укрупнение 1",
        "enlargement2": "Укрупнение 2",
        "properties": "Свойства",
        "status": "Статус",
        "note": "Примечание",
        "enlargementCode": "Код УБР",
        "enlargementName": "Наименование УБР",
        "enlargementCoef": "Коэф. перевода",
        "workerHoursPerUnit": "чел.-час./ед.",
        "machineHoursPerUnit": "маш.-час./ед.",
        "moneyPerHour": "руб./час.",
        "moneyPerUnit": "руб./ед.",
        "calculation": "Калькуляция",
        "temporaryRegulations": "Временные нормы",
        "canceled": "Аннулированно",
        "noData": "Нет данных",
        "loadCustomUpgHeader": "Загрузите свой Справочник Единичных Расценок",
        "chooseRegion": "Выберите регион",
        "chooseFile": "Выберите файл",
        "uploadFile": "Загрузить"
    },

    "smtr": {
        "index": "№ п/п",
        "stage": "Стадия",
        "title": "Титул",
        "titleName": "Наименование титула",
        "brand": "Марка / Том",
        "techSpecCode": "Номер (шифр)  тех. спецификации / чертежа",
        "revision": "Рев. тех. док.",
        "constructive": "Конструктив", // end
        "position": "Позиция по спец.",
        "techName": "Наименование и техническая характеристика",
        "docType": "Тип, марка, обозначение  документа / опросного листа",
        "code": "Код продукции",
        "manufacturer": "Завод изготовитель / Поставщик",
        "units": "Ед. изм.",
        "quantityInProject": "Кол-во по проекту",
        "mass": "Масса 1 ед., кг",
        "note": "Примечания",
        "consumptionRate": "Норма расхода, %",
        "consumptionQuantity": "Кол-во с учетом нормы расхода", // end
        "resourceType": "Тип",
        "delivery": "Разделение поставки",
        "pricePerUnit": "Цена за ед., без НДС, руб",
        "cost": "Стоимость МТР, без НДС, руб", // end
        "workCode": "Код работ",
        "workName": "Наименование работ",
        "coeficient": "K",
        "quantity": "Кол-во"
    },

    "structure": {
        "title": "Титул",
        "name": "Наименование титула",
        "mark": "Том",
        "code": "Шифр проекта",
        "type": "Тип",        
        "date": "Дата выдачи РД"
    },

    "tasks": {
        "header": "Задачи"
    }
}

// export type LocalizationType = typeof defaultLocalization;
export default defaultLocalization;